//! OpenAPI 3.1 spec + Swagger UI mount.
//!
//! Generated by [`utoipa`] from `#[utoipa::path]` annotations on handlers.
//! Served at (only when [`AppState::docs_enabled`] is `true`; config flag
//! `docs.enabled`, env `PHARMA__DOCS__ENABLED` — on a hardened on-prem box the
//! operator flips it off to keep the API surface off the wire):
//! * `/docs` — Swagger UI (HTML).
//! * `/docs/openapi.json` — raw spec.
//!
//! Schema strategy (Fase 11/erp-parity):
//! * The `ErrorEnvelope` envelope is registered with full `ToSchema`.
//! * Domain DTOs live in `crates/domain` which API mustn't touch this slice;
//!   their request/response bodies are surfaced as opaque `object` (via
//!   `body = serde_json::Value`) until a later PR brings `ToSchema` derives
//!   into the domain crate. Endpoint paths, methods, tags, security and
//!   error codes are all documented today — schemas come in the next slice.

use axum::Router;
use utoipa::{
    openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme},
    Modify, OpenApi,
};
use utoipa_swagger_ui::SwaggerUi;

use crate::error::{ErrorBody, ErrorEnvelope};
use crate::AppState;

/// Mount point for the interactive Swagger UI.
pub const SWAGGER_UI_PATH: &str = "/docs";
/// Path the OpenAPI JSON is served at (and the URL Swagger UI fetches).
pub const OPENAPI_JSON_PATH: &str = "/docs/openapi.json";

/// Bearer-JWT security scheme injector. Registered as `bearer_jwt` so each
/// handler annotation can opt-in via `security(("bearer_jwt" = []))`.
pub struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_jwt",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .description(Some(
                            "JWT HS256 emitido por `POST /api/v1/auth/login`. \
                             Claim `roles: [\"cashier\"|\"pharmacist\"|\"admin\"|\"owner\"]`.",
                        ))
                        .build(),
                ),
            );
        }
    }
}

#[derive(OpenApi)]
#[openapi(
    info(
        title = "pharma-server API",
        version = env!("CARGO_PKG_VERSION"),
        description = "API HTTP del servidor on-prem pharma-server.\n\n\
            * Multi-tenant via JWT claim `tenant_id`.\n\
            * Roles granulares: cashier / pharmacist / admin / owner.\n\
            * Errores en español (campo `message`); códigos estables en \
              inglés SCREAMING_SNAKE (campo `code`).\n\
            * Idempotencia: `POST /api/v1/pos/sale` honra `Idempotency-Key`.\n\
            * Tier license: endpoints marcados con 402 `FEATURE_REQUIRES_UPGRADE` \
              requieren plan superior — ver `docs/strategy/freemium-master-plan.md`.",
        contact(name = "pharma-server", url = "https://github.com/pabloalvarez99/pharma-server"),
        license(name = "Proprietary"),
    ),
    servers(
        (url = "http://localhost:8080", description = "Local dev / MSI install"),
    ),
    tags(
        (name = "Sales", description = "POS, devoluciones, settings, interacciones."),
        (name = "Inventory", description = "Stock, lotes, faltas, ABC, reorder."),
        (name = "Catalog", description = "Productos, categorías, etiquetas, precios."),
        (name = "CashRegister", description = "Apertura, cierre, arqueo, movimientos de caja."),
        (name = "Customers", description = "Clientes y loyalty (read-only)."),
        (name = "Prescriptions", description = "Recetas y libro de controlados (Ley 20.000)."),
    ),
    paths(
        // Sales
        crate::v1::sales::post_sale,
        crate::v1::sales::list_orders,
        crate::v1::sales::get_order,
        crate::v1::sales::create_refund,
        crate::v1::sales::list_refunds,
        crate::v1::sales::check_interactions,
        crate::v1::sales::get_setting,
        crate::v1::sales::set_setting,
        // Inventory
        crate::v1::inventory::list_movements,
        crate::v1::inventory::create_movement,
        crate::v1::inventory::adjust_movement,
        crate::v1::inventory::import_movements,
        crate::v1::inventory::list_batches,
        crate::v1::inventory::get_batch,
        crate::v1::inventory::create_batch,
        crate::v1::inventory::update_batch_h,
        crate::v1::inventory::delete_batch_h,
        crate::v1::inventory::list_faltas,
        crate::v1::inventory::create_falta_h,
        crate::v1::inventory::update_falta_h,
        crate::v1::inventory::summary,
        crate::v1::inventory::abc,
        crate::v1::inventory::reorder_suggestions,
        // Catalog
        crate::v1::catalog::list_products,
        crate::v1::catalog::get_product,
        crate::v1::catalog::product_stats,
        crate::v1::catalog::etiquetas,
        crate::v1::catalog::export_products,
        crate::v1::catalog::create_product,
        crate::v1::catalog::update_product,
        crate::v1::catalog::delete_product,
        crate::v1::catalog::adjust_stock,
        crate::v1::catalog::import_products,
        crate::v1::catalog::bulk_price,
        crate::v1::catalog::update_prices,
        crate::v1::catalog::list_categories,
        crate::v1::catalog::get_category,
        crate::v1::catalog::create_category,
        crate::v1::catalog::update_category,
        crate::v1::catalog::delete_category,
        // CashRegister
        crate::v1::cash_register::open_session,
        crate::v1::cash_register::list_sessions,
        crate::v1::cash_register::get_session,
        crate::v1::cash_register::arqueo,
        crate::v1::cash_register::close_session,
        crate::v1::cash_register::add_movement,
        crate::v1::cash_register::list_movements,
        // Customers
        crate::v1::customers::list_customers,
        crate::v1::customers::get_customer,
        crate::v1::customers::create_customer,
        crate::v1::customers::update_customer,
        crate::v1::customers::delete_customer,
        crate::v1::customers::list_loyalty,
        crate::v1::customers::loyalty_stats,
        // Prescriptions
        crate::v1::prescriptions::list_prescriptions,
        crate::v1::prescriptions::get_prescription,
        crate::v1::prescriptions::create_prescription,
        crate::v1::prescriptions::list_libro,
        crate::v1::prescriptions::export_libro,
        crate::v1::prescriptions::list_shifts,
        crate::v1::prescriptions::create_shift,
        crate::v1::prescriptions::update_shift,
    ),
    components(schemas(ErrorEnvelope, ErrorBody)),
    modifiers(&SecurityAddon),
)]
pub struct ApiDoc;

/// Build the Swagger UI + OpenAPI JSON sub-router, or an empty router when docs
/// are disabled (`docs.enabled = false`). Merged into the top-level router in
/// [`crate::build_router`]. When disabled, both `/docs` and
/// `/docs/openapi.json` 404 — keeps the API surface off the wire on hardened
/// on-prem deployments.
pub fn router(state: &AppState) -> Router<AppState> {
    if state.docs_enabled {
        SwaggerUi::new(SWAGGER_UI_PATH)
            .url(OPENAPI_JSON_PATH, ApiDoc::openapi())
            .into()
    } else {
        Router::new()
    }
}
