[package]
name = "cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pharma"
path = "src/main.rs"

[dependencies]
pharma-core = { path = "../core" }
db = { path = "../db" }
auth = { path = "../auth" }
agent = { path = "../agent" }
license = { path = "../license" }
chrono.workspace = true
uuid.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
clap.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
telemetry = { path = "../telemetry" }
serde_json.workspace = true
serde.workspace = true
rpassword.workspace = true
surrealdb.workspace = true

[dev-dependencies]
httpmock = "0.7"
tempfile = "3"
