/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.apis

import cl.rutbusiness.core.api.models.ErrorEnvelope

import cl.rutbusiness.core.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class CashRegisterApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * Crea movimiento de caja (in/out manual). Requiere cashier+.
     * 
     * @param id 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun addMovement(id: kotlin.String, body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/cash-sessions/{id}/movements".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Arqueo preview de una caja (estado, totales).
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun arqueo(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/cash-sessions/{id}/arqueo".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Cierre de caja con conteo real (calcula diferencia). Requiere cashier+.
     * 
     * @param id 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun closeSession(id: kotlin.String, body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/cash-sessions/{id}/close".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Detalle de una cash session.
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getSession(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/cash-sessions/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Lista movimientos de una caja.
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listMovements(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/cash-sessions/{id}/movements".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Lista cash sessions del tenant.
     * 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listSessions(): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/cash-sessions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Apertura de caja. Requiere cashier+.
     * 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun openSession(body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/cash-sessions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
