/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.apis

import cl.rutbusiness.core.api.models.ErrorEnvelope
import cl.rutbusiness.core.api.models.NewVariant
import cl.rutbusiness.core.api.models.ProductDto

import cl.rutbusiness.core.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class CatalogApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * Ajuste rápido de stock por producto (atajo de stock-movements). Requiere admin+.
     * 
     * @param id 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun adjustStock(id: kotlin.String, body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/products/{id}/stock".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Bulk update de precios por % o monto. Requiere admin+.
     * 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun bulkPrice(body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/products/bulk-price",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Crea categoría. Requiere admin+.
     * 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createCategory(body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/categories",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Crea un producto. Requiere admin+.
     * 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createProduct(body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/products",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Crea una variante vendible bajo el producto padre (stock + barcode propios). El padre puede no tener barcode de caja. Barcode de variante es tenant-único (409).
     * 
     * @param id Id del producto padre
     * @param newVariant 
     * @return ProductDto
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createVariant(id: kotlin.String, newVariant: NewVariant): HttpResponse<ProductDto> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = newVariant

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/products/{id}/variants".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Elimina (soft) categoría. Requiere admin+.
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteCategory(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v1/categories/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Elimina (soft) un producto. Requiere admin+.
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteProduct(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v1/products/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Elimina (soft) una variante multi-SKU. Requiere admin+.
     * Soft-delete (&#x60;active &#x3D; false&#x60;); conserva stock y movimientos (ledger). Libera el barcode del hijo para reasignación. No borra el padre. Rechaza si &#x60;variant_id&#x60; no es hijo de &#x60;{id}&#x60;.  **Editar variante**: usar &#x60;PATCH /api/v1/products/{variant_id}&#x60; (nombre, precio, attrs, &#x60;active&#x60;, &#x60;barcode&#x60;). Stock: &#x60;POST .../stock&#x60;.
     * @param id Id del producto padre
     * @param variantId Id de la variante (hijo)
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteVariant(id: kotlin.String, variantId: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v1/products/{id}/variants/{variant_id}".replace("{" + "id" + "}", "$id").replace("{" + "variant_id" + "}", "$variantId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Autocomplete de etiquetas (laboratorio, ingrediente, acción).
     * 
     * @param q Substring de búsqueda
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun etiquetas(q: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/etiquetas/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Exporta catálogo como CSV.
     * 
     * @return void
     */
    open suspend fun exportProducts(): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/products/export",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Resuelve un código de barras del tenant al producto vendible (variante o SKU plano). Nunca devuelve el padre abstracto: el mapping apunta al hijo o SKU plano.
     * 
     * @param code EAN/UPC u otro barcode del local
     * @return ProductDto
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getByBarcode(code: kotlin.String): HttpResponse<ProductDto> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/products/by-barcode/{code}".replace("{" + "code" + "}", "$code"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Detalle de una categoría.
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getCategory(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/categories/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Detalle de un producto.
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getProduct(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/products/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Import CSV de productos (multipart). Requiere admin+. Con &#x60;?dry_run&#x3D;true&#x60; valida y cuenta SIN escribir nada (preview antes de confirmar).
     * 
     * @param dryRun Valida sin escribir (preview) (optional)
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun importProducts(dryRun: kotlin.Boolean? = null): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        dryRun?.apply { localVariableQuery["dry_run"] = listOf("$dryRun") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/products/import",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Lista categorías del catálogo.
     * 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listCategories(): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/categories",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Lista productos del tenant. Por defecto oculta variantes hijas (&#x60;parent_id&#x60;); pasar &#x60;?include_variants&#x3D;true&#x60; para verlas, o usar &#x60;GET .../variants&#x60;.
     * 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listProducts(): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/products",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Lista variantes (hijos multi-SKU) de un producto padre. Orden: &#x60;name&#x60; ASC. Cada ítem incluye &#x60;stock&#x60; propio y &#x60;barcode&#x60; si existe.
     * 
     * @param id Id del producto padre
     * @return kotlin.collections.List<ProductDto>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listVariants(id: kotlin.String): HttpResponse<kotlin.collections.List<ProductDto>> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/products/{id}/variants".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<ListVariantsResponse>().map { value }
    }

    @Serializable(ListVariantsResponse.Companion::class)
    private class ListVariantsResponse(val value: List<ProductDto>) {
        companion object : KSerializer<ListVariantsResponse> {
            private val serializer: KSerializer<List<ProductDto>> = serializer<List<ProductDto>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: ListVariantsResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = ListVariantsResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Estadísticas de catálogo (totales, sin stock, etc.).
     * 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun productStats(): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/products/stats",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Actualiza categoría. Requiere admin+.
     * 
     * @param id 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateCategory(id: kotlin.String, body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PATCH,
            "/api/v1/categories/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Reprice from &#x60;supplier_price_list&#x60;. That table arrives in Fase 5 (purchasing); endpoint shape is reserved now, returns 501.
     * 
     * @return void
     */
    open suspend fun updatePrices(): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/products/update-prices",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Actualiza un producto (patch). Requiere admin+.
     * 
     * @param id 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateProduct(id: kotlin.String, body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PATCH,
            "/api/v1/products/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
