/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.apis

import cl.rutbusiness.core.api.models.ErrorEnvelope

import cl.rutbusiness.core.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class ConfigCenterApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * Crea una sucursal. Requiere admin+.
     * 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createBranch(body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/sucursales",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Crea una caja. Requiere admin+. &#x60;branch&#x60; opcional; debe ser del tenant.
     * 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createRegister(body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/cajas",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Desactiva (soft delete) una sucursal. Requiere admin+.
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteBranch(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v1/sucursales/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Desactiva (soft delete) una caja. Requiere admin+.
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteRegister(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v1/cajas/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Detalle de una sucursal.
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getBranch(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/sucursales/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Detalle de una caja.
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getRegister(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/cajas/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Lista sucursales del tenant. &#x60;?active&#x3D;false&#x60; para ver inactivas.
     * 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listBranches(): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/sucursales",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Lista cajas del tenant. &#x60;?active&#x3D;false&#x60; para ver inactivas; &#x60;?branch&#x3D;...&#x60; filtra por sucursal.
     * 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listRegisters(): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/cajas",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Actualiza una sucursal. Requiere admin+.
     * 
     * @param id 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateBranch(id: kotlin.String, body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PATCH,
            "/api/v1/sucursales/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Actualiza una caja. Requiere admin+. &#x60;branch&#x60; (si viene) debe ser del tenant.
     * 
     * @param id 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateRegister(id: kotlin.String, body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PATCH,
            "/api/v1/cajas/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
