/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.apis

import cl.rutbusiness.core.api.models.ErrorEnvelope

import cl.rutbusiness.core.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class CustomersApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * Crea cliente. Requiere cashier+.
     * 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createCustomer(body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/clientes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Elimina (soft) cliente. Requiere cashier+.
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteCustomer(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v1/clientes/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Detalle de cliente.
     * 
     * @param id 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getCustomer(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/clientes/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Lista clientes del tenant.
     * 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listCustomers(): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/clientes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Lista del ledger de loyalty (sólo lectura).
     * 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listLoyalty(): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/loyalty",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Estadísticas de loyalty.
     * 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun loyaltyStats(): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/loyalty/stats",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Actualiza cliente. Requiere cashier+.
     * 
     * @param id 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateCustomer(id: kotlin.String, body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PATCH,
            "/api/v1/clientes/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
