/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.apis

import cl.rutbusiness.core.api.models.ErrorEnvelope

import cl.rutbusiness.core.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class SalesApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * Preview interactions without committing a sale. The POS calls this when the cart changes to surface warnings live (badge in UI, etc.). Pre-check de interacciones farmacológicas sin commit.
     * 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun checkInteractions(body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/interactions/check",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Crear devolución (refund) parcial o total de un pedido.
     * 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createRefund(body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/pos/returns",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Detalle de un pedido (cabecera + items).
     * 
     * @param id Order record id (order:xxx)
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getOrder(id: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/orders/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Lee un admin_setting por key.
     * 
     * @param key Setting key
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getSetting(key: kotlin.String): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/settings/{key}".replace("{" + "key" + "}", "$key"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Lista de pedidos (orders) del tenant. Filtros por fecha, cliente, etc.
     * 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listOrders(): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/orders",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Lista de devoluciones del tenant.
     * 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listRefunds(): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/returns",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Vender en POS. Crea pedido + movimientos + descuento de stock + asiento de caja en una sola tx. Honra &#x60;Idempotency-Key&#x60;.
     * 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postSale(body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/pos/sale",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Crea o actualiza un admin_setting. Requiere admin+.
     * 
     * @param key 
     * @param body 
     * @return kotlinx.serialization.json.JsonElement
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun setSetting(key: kotlin.String, body: kotlinx.serialization.json.JsonElement): HttpResponse<kotlinx.serialization.json.JsonElement> {

        val localVariableAuthNames = listOf<String>("bearer_jwt")

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/api/v1/settings/{key}".replace("{" + "key" + "}", "$key"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
