/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param scopes Defaults to `[\"catalog:read\", \"orders:write\"]`.
 */
@Serializable

data class CreateKeyRequest (

    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Defaults to `[\"catalog:read\", \"orders:write\"]`. */
    @SerialName(value = "scopes") val scopes: kotlin.collections.List<kotlin.String>? = null

) {


}

