/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Create/rotate response — the ONLY place the plaintext key and HMAC secret ever appear.
 *
 * @param hmacSecret Plaintext `whsec_…` signing secret. Shown once; store it now.
 * @param id 
 * @param key Plaintext `rb_live_…` key. Shown once; store it now.
 * @param name 
 * @param scopes 
 * @param keyPrefix 
 */
@Serializable

data class CreatedKeyResponse (

    /* Plaintext `whsec_…` signing secret. Shown once; store it now. */
    @SerialName(value = "hmac_secret") @Required val hmacSecret: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    /* Plaintext `rb_live_…` key. Shown once; store it now. */
    @SerialName(value = "key") @Required val key: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "scopes") @Required val scopes: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "key_prefix") val keyPrefix: kotlin.String? = null

) {


}

