/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cantidad 
 * @param nombre 
 * @param precioUnitario 
 * @param exento 
 */
@Serializable

data class DocItemReq (

    @SerialName(value = "cantidad") @Required val cantidad: kotlin.String,

    @SerialName(value = "nombre") @Required val nombre: kotlin.String,

    @SerialName(value = "precio_unitario") @Required val precioUnitario: kotlin.String,

    @SerialName(value = "exento") val exento: kotlin.Boolean? = null

) {


}

