/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models

import cl.rutbusiness.core.api.models.DocItemReq
import cl.rutbusiness.core.api.models.ReceptorReq
import cl.rutbusiness.core.api.models.ReferenciaReq

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param certPassphrase 
 * @param items 
 * @param receptor 
 * @param tipo Tipo SII: 33 factura, 56 nota débito, 61 nota crédito, 52 guía.
 * @param indTraslado Motivo del traslado (guía 52): 1 venta … 9 venta exportación.
 * @param orderId Link opcional a la orden POS de origen.
 * @param referencias 
 */
@Serializable

data class EmitDocumentoRequest (

    @SerialName(value = "cert_passphrase") @Required val certPassphrase: kotlin.String,

    @SerialName(value = "items") @Required val items: kotlin.collections.List<DocItemReq>,

    @SerialName(value = "receptor") @Required val receptor: ReceptorReq,

    /* Tipo SII: 33 factura, 56 nota débito, 61 nota crédito, 52 guía. */
    @SerialName(value = "tipo") @Required val tipo: kotlin.Int,

    /* Motivo del traslado (guía 52): 1 venta … 9 venta exportación. */
    @SerialName(value = "ind_traslado") val indTraslado: kotlin.Int? = null,

    /* Link opcional a la orden POS de origen. */
    @SerialName(value = "order_id") val orderId: kotlin.String? = null,

    @SerialName(value = "referencias") val referencias: kotlin.collections.List<ReferenciaReq>? = null

) {


}

