/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param code SCREAMING_SNAKE machine-readable code. Stable contract.
 * @param message User-facing message in Spanish.
 * @param details Optional free-form payload for field-level errors / retry hints.
 */
@Serializable

data class ErrorBody (

    /* SCREAMING_SNAKE machine-readable code. Stable contract. */
    @SerialName(value = "code") @Required val code: kotlin.String,

    /* User-facing message in Spanish. */
    @SerialName(value = "message") @Required val message: kotlin.String,

    /* Optional free-form payload for field-level errors / retry hints. */
    @SerialName(value = "details") val details: kotlin.String? = null

) {


}

