/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param certPassphrase Passphrase del cert digital (la misma del PFX importado).
 * @param period Período contable `YYYY-MM`.
 */
@Serializable

data class LibroSignedReq (

    /* Passphrase del cert digital (la misma del PFX importado). */
    @SerialName(value = "cert_passphrase") @Required val certPassphrase: kotlin.String,

    /* Período contable `YYYY-MM`. */
    @SerialName(value = "period") @Required val period: kotlin.String

) {


}

