/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Input to create a sellable variant under a parent product (migración 0034). Stock and barcode live on the child; `attrs` carries talla/color/sku.
 *
 * @param attrs 
 * @param barcode EAN / barcode of this SKU (tenant-unique). POS scan resolves here.
 * @param costPrice 
 * @param externalId 
 * @param imageUrl 
 * @param name Display name; defaults to `{parent.name} — {talla/color/sku}` when omitted.
 * @param price Unit price; inherits parent when omitted.
 * @param slug Optional; auto-generated tenant-unique slug if omitted.
 * @param stock 
 */
@Serializable

data class NewVariant (

    @SerialName(value = "attrs") val attrs: kotlinx.serialization.json.JsonElement? = null,

    /* EAN / barcode of this SKU (tenant-unique). POS scan resolves here. */
    @SerialName(value = "barcode") val barcode: kotlin.String? = null,

    @SerialName(value = "cost_price") val costPrice: kotlin.String? = null,

    @SerialName(value = "external_id") val externalId: kotlin.String? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null,

    /* Display name; defaults to `{parent.name} — {talla/color/sku}` when omitted. */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* Unit price; inherits parent when omitted. */
    @SerialName(value = "price") val price: kotlin.String? = null,

    /* Optional; auto-generated tenant-unique slug if omitted. */
    @SerialName(value = "slug") val slug: kotlin.String? = null,

    @SerialName(value = "stock") val stock: kotlin.Long? = null

) {


}

