/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param active 
 * @param createdAt 
 * @param id 
 * @param name 
 * @param physicalStock `false` = servicio (no descuenta inventario, sin lotes). DEFAULT `true` en DB (migración 0031): todo producto físico mantiene el chequeo de stock.
 * @param prescriptionType 
 * @param price 
 * @param slug 
 * @param stock 
 * @param updatedAt 
 * @param activeIngredient 
 * @param attrs 
 * @param barcode Tenant barcode from `product_barcode` when present (enriched on read / create-variant). Plain products and parents often omit it (caja en hijos).
 * @param category 
 * @param costPrice 
 * @param description 
 * @param discountPercent 
 * @param externalId 
 * @param imageUrl 
 * @param laboratory 
 * @param parentId Parent product when this row is a sellable variant (migration 0034, Opción A). `None` = product plano o padre de matriz de tallas.
 * @param presentation 
 * @param therapeuticAction 
 * @param variantCount Count of active children (list badge without N+1). Present iff parent has ≥1 active variant — same keying as `variants_stock`.
 * @param variantsStock Read-side sum of **active** children stock when this row is a multi-SKU parent. Never written to `product.stock` (ledger invariant + farmacia plain SKUs keep stock on the product itself).
 */
@Serializable

data class ProductDto (

    @SerialName(value = "active") @Required val active: kotlin.Boolean,

    @SerialName(value = "created_at") @Required val createdAt: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    /* `false` = servicio (no descuenta inventario, sin lotes). DEFAULT `true` en DB (migración 0031): todo producto físico mantiene el chequeo de stock. */
    @SerialName(value = "physical_stock") @Required val physicalStock: kotlin.Boolean,

    @SerialName(value = "prescription_type") @Required val prescriptionType: kotlin.String,

    @SerialName(value = "price") @Required val price: kotlin.String,

    @SerialName(value = "slug") @Required val slug: kotlin.String,

    @SerialName(value = "stock") @Required val stock: kotlin.Long,

    @SerialName(value = "updated_at") @Required val updatedAt: kotlin.String,

    @SerialName(value = "active_ingredient") val activeIngredient: kotlin.String? = null,

    @SerialName(value = "attrs") val attrs: kotlinx.serialization.json.JsonElement? = null,

    /* Tenant barcode from `product_barcode` when present (enriched on read / create-variant). Plain products and parents often omit it (caja en hijos). */
    @SerialName(value = "barcode") val barcode: kotlin.String? = null,

    @SerialName(value = "category") val category: kotlin.String? = null,

    @SerialName(value = "cost_price") val costPrice: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "discount_percent") val discountPercent: kotlin.Long? = null,

    @SerialName(value = "external_id") val externalId: kotlin.String? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null,

    @SerialName(value = "laboratory") val laboratory: kotlin.String? = null,

    /* Parent product when this row is a sellable variant (migration 0034, Opción A). `None` = product plano o padre de matriz de tallas. */
    @SerialName(value = "parent_id") val parentId: kotlin.String? = null,

    @SerialName(value = "presentation") val presentation: kotlin.String? = null,

    @SerialName(value = "therapeutic_action") val therapeuticAction: kotlin.String? = null,

    /* Count of active children (list badge without N+1). Present iff parent has ≥1 active variant — same keying as `variants_stock`. */
    @SerialName(value = "variant_count") val variantCount: kotlin.Long? = null,

    /* Read-side sum of **active** children stock when this row is a multi-SKU parent. Never written to `product.stock` (ledger invariant + farmacia plain SKUs keep stock on the product itself). */
    @SerialName(value = "variants_stock") val variantsStock: kotlin.Long? = null

) {


}

