/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param currency Always \"CLP\" for now.
 * @param name 
 * @param pickupEnabled `true` in PR1 (pickup is the only fulfillment until PR3).
 * @param slug Tenant slug (the `{slug}` path segment).
 * @param addressLine 
 * @param hoursLabel 
 * @param pickupInstructions 
 * @param whatsappE164 
 */
@Serializable

data class PublicStoreDto (

    /* Always \"CLP\" for now. */
    @SerialName(value = "currency") @Required val currency: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    /* `true` in PR1 (pickup is the only fulfillment until PR3). */
    @SerialName(value = "pickup_enabled") @Required val pickupEnabled: kotlin.Boolean,

    /* Tenant slug (the `{slug}` path segment). */
    @SerialName(value = "slug") @Required val slug: kotlin.String,

    @SerialName(value = "address_line") val addressLine: kotlin.String? = null,

    @SerialName(value = "hours_label") val hoursLabel: kotlin.String? = null,

    @SerialName(value = "pickup_instructions") val pickupInstructions: kotlin.String? = null,

    @SerialName(value = "whatsapp_e164") val whatsappE164: kotlin.String? = null

) {


}

