/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models

import cl.rutbusiness.core.api.models.PublicAvailability

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param availability Coarse availability from `stock` — never the integer count.
 * @param id Record id (`product:xyz`).
 * @param name `online_title ?? name`.
 * @param priceClp `online_price ?? price`.
 * @param slug 
 * @param categorySlug 
 * @param descriptionShort `online_description ?? description`.
 * @param imageUrl 
 */
@Serializable

data class PublicProductDto (

    /* Coarse availability from `stock` — never the integer count. */
    @SerialName(value = "availability") @Required val availability: PublicAvailability,

    /* Record id (`product:xyz`). */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* `online_title ?? name`. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* `online_price ?? price`. */
    @SerialName(value = "price_clp") @Required val priceClp: kotlin.String,

    @SerialName(value = "slug") @Required val slug: kotlin.String,

    @SerialName(value = "category_slug") val categorySlug: kotlin.String? = null,

    /* `online_description ?? description`. */
    @SerialName(value = "description_short") val descriptionShort: kotlin.String? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null

) {


}

