/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models

import cl.rutbusiness.core.api.models.PublicProductDto
import cl.rutbusiness.core.api.models.PublicStoreDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param items 
 * @param store 
 * @param nextOffset `Some` when a full page was returned (there may be more rows).
 */
@Serializable

data class PublicCatalogPage (

    @SerialName(value = "items") @Required val items: kotlin.collections.List<PublicProductDto>,

    @SerialName(value = "store") @Required val store: PublicStoreDto,

    /* `Some` when a full page was returned (there may be more rows). */
    @SerialName(value = "next_offset") val nextOffset: kotlin.Int? = null

) {


}

