/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One line of a goods receipt against a sent/approved purchase order. `po_line_id` targets the `purchase_order_item`; `qty_received` is the quantity that physically arrived in *this* receipt (additive across partial receipts, capped at the line's remaining-to-receive).
 *
 * @param poLineId `purchase_order_item:xxx` — the line being received.
 * @param qtyReceived 
 * @param expiryDate 
 * @param lot Optional lot/batch code. When present (with `expiry_date`) a `product_batch` row is created/topped-up for traceability.
 */
@Serializable

data class ReceivePurchaseOrderLine (

    /* `purchase_order_item:xxx` — the line being received. */
    @SerialName(value = "po_line_id") @Required val poLineId: kotlin.String,

    @SerialName(value = "qty_received") @Required val qtyReceived: kotlin.Long,

    @SerialName(value = "expiry_date") val expiryDate: kotlin.String? = null,

    /* Optional lot/batch code. When present (with `expiry_date`) a `product_batch` row is created/topped-up for traceability. */
    @SerialName(value = "lot") val lot: kotlin.String? = null

) {


}

