/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models

import cl.rutbusiness.core.api.models.ReceivePurchaseOrderLine

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param lines 
 * @param notes 
 */
@Serializable

data class ReceivePurchaseOrder (

    @SerialName(value = "lines") @Required val lines: kotlin.collections.List<ReceivePurchaseOrderLine>,

    @SerialName(value = "notes") val notes: kotlin.String? = null

) {


}

