/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param comuna 
 * @param direccion 
 * @param giro 
 * @param razonSocial 
 * @param rut 
 */
@Serializable

data class ReceptorReq (

    @SerialName(value = "comuna") @Required val comuna: kotlin.String,

    @SerialName(value = "direccion") @Required val direccion: kotlin.String,

    @SerialName(value = "giro") @Required val giro: kotlin.String,

    @SerialName(value = "razon_social") @Required val razonSocial: kotlin.String,

    @SerialName(value = "rut") @Required val rut: kotlin.String

) {


}

