/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param fechaRef Fecha del documento referenciado, YYYY-MM-DD.
 * @param folioRef 
 * @param tipoDocRef Código SII del doc referenciado (\"33\", \"39\", \"61\", \"52\", \"801\"…).
 * @param codRef 1 anula, 2 corrige texto, 3 corrige montos (obligatorio en notas).
 * @param razonRef 
 */
@Serializable

data class ReferenciaReq (

    /* Fecha del documento referenciado, YYYY-MM-DD. */
    @SerialName(value = "fecha_ref") @Required val fechaRef: kotlin.String,

    @SerialName(value = "folio_ref") @Required val folioRef: kotlin.String,

    /* Código SII del doc referenciado (\"33\", \"39\", \"61\", \"52\", \"801\"…). */
    @SerialName(value = "tipo_doc_ref") @Required val tipoDocRef: kotlin.String,

    /* 1 anula, 2 corrige texto, 3 corrige montos (obligatorio en notas). */
    @SerialName(value = "cod_ref") val codRef: kotlin.Int? = null,

    @SerialName(value = "razon_ref") val razonRef: kotlin.String? = null

) {


}

