/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param certPassphrase Passphrase del PFX (la misma que se teclea al emitir). No se persiste.
 * @param pfxBase64 Certificado digital PFX/PKCS#12 codificado en base64.
 * @param rut RUT del propietario del cert (`12345678-9`).
 * @param vigenciaDesde Vigencia desde (YYYY-MM-DD).
 * @param vigenciaHasta Vigencia hasta (YYYY-MM-DD).
 */
@Serializable

data class UploadCertRequest (

    /* Passphrase del PFX (la misma que se teclea al emitir). No se persiste. */
    @SerialName(value = "cert_passphrase") @Required val certPassphrase: kotlin.String,

    /* Certificado digital PFX/PKCS#12 codificado en base64. */
    @SerialName(value = "pfx_base64") @Required val pfxBase64: kotlin.String,

    /* RUT del propietario del cert (`12345678-9`). */
    @SerialName(value = "rut") @Required val rut: kotlin.String,

    /* Vigencia desde (YYYY-MM-DD). */
    @SerialName(value = "vigencia_desde") @Required val vigenciaDesde: kotlin.String,

    /* Vigencia hasta (YYYY-MM-DD). */
    @SerialName(value = "vigencia_hasta") @Required val vigenciaHasta: kotlin.String

) {


}

