/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Listing/CRUD row. Never carries `key_hash` nor `hmac_secret` — the SELECT projections below are the enforcement point.
 *
 * @param active 
 * @param createdAt 
 * @param id Full record id, e.g. `api_key:x1y2z3`.
 * @param name 
 * @param scopes 
 * @param keyPrefix First chars of the plaintext (incl. `rb_live_`) for display. `None` for 0026-era CLI-minted keys.
 * @param lastUsedAt 
 */
@Serializable

data class WebKeyDto (

    @SerialName(value = "active") @Required val active: kotlin.Boolean,

    @SerialName(value = "created_at") @Required val createdAt: kotlin.String,

    /* Full record id, e.g. `api_key:x1y2z3`. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "scopes") @Required val scopes: kotlin.collections.List<kotlin.String>,

    /* First chars of the plaintext (incl. `rb_live_`) for display. `None` for 0026-era CLI-minted keys. */
    @SerialName(value = "key_prefix") val keyPrefix: kotlin.String? = null,

    @SerialName(value = "last_used_at") val lastUsedAt: kotlin.String? = null

) {


}

