/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 201 body — PR4 (storefront scripts) and PR5 (proxy) depend on these exact field names.
 *
 * @param currency 
 * @param expiresAt 
 * @param orderId 
 * @param pickupCode 
 * @param status 
 * @param total Total CLP as decimal string (server-computed; client prices ignored).
 */
@Serializable

data class WebPickupOrderResponse (

    @SerialName(value = "currency") @Required val currency: kotlin.String,

    @SerialName(value = "expires_at") @Required val expiresAt: kotlin.String,

    @SerialName(value = "order_id") @Required val orderId: kotlin.String,

    @SerialName(value = "pickup_code") @Required val pickupCode: kotlin.String,

    @SerialName(value = "status") @Required val status: kotlin.String,

    /* Total CLP as decimal string (server-computed; client prices ignored). */
    @SerialName(value = "total") @Required val total: kotlin.String

) {


}

