/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models

import cl.rutbusiness.core.api.models.WebPickupCustomer
import cl.rutbusiness.core.api.models.WebPickupFulfillment
import cl.rutbusiness.core.api.models.WebPickupItem

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * `POST /api/v1/public/{slug}/orders/web` body. Serialize is required for the idempotency body fingerprint (same canonical-bytes scheme as [`PosSaleRequest`]). Distinct from the legacy push-ingest `sales::web_order::WebOrderRequest` (different seam, different contract).
 *
 * @param customer 
 * @param items 
 * @param fulfillment 
 */
@Serializable

data class WebPickupOrderRequest (

    @SerialName(value = "customer") @Required val customer: WebPickupCustomer,

    @SerialName(value = "items") @Required val items: kotlin.collections.List<WebPickupItem>,

    @SerialName(value = "fulfillment") val fulfillment: WebPickupFulfillment? = null

) {


}

