/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param productId Product record id (`product:xxx`) as exposed by the public catalog.
 * @param qty 
 */
@Serializable

data class WebPickupItem (

    /* Product record id (`product:xxx`) as exposed by the public catalog. */
    @SerialName(value = "product_id") @Required val productId: kotlin.String,

    @SerialName(value = "qty") @Required val qty: kotlin.Long

) {


}

