/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cl.rutbusiness.core.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param notes 
 * @param type Only `pickup` is accepted in PR3 (`delivery` reserved for later).
 */
@Serializable

data class WebPickupFulfillment (

    @SerialName(value = "notes") val notes: kotlin.String? = null,

    /* Only `pickup` is accepted in PR3 (`delivery` reserved for later). */
    @SerialName(value = "type") val type: kotlin.String? = null

) {


}

