[package]
name = "api"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pharma-api"
path = "src/main.rs"

[dependencies]
pharma-core = { path = "../core" }
db = { path = "../db" }
auth = { path = "../auth" }
domain = { path = "../domain" }
agent = { path = "../agent" }
license = { path = "../license" }
arc-swap.workspace = true
telemetry = { path = "../telemetry" }
tokio.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
utoipa.workspace = true
utoipa-axum.workspace = true
utoipa-swagger-ui.workspace = true
axum-prometheus.workspace = true
chrono.workspace = true
surrealdb.workspace = true
uuid.workspace = true
csv.workspace = true
sha2 = "0.10"
hmac.workspace = true
hex.workspace = true
reqwest.workspace = true
tar.workspace = true
flate2.workspace = true
tokio-cron-scheduler.workspace = true

[dev-dependencies]
tower = { workspace = true }
http-body-util = "0.1"
hyper = "1"
tempfile = "3"
flate2.workspace = true
tar.workspace = true
serde_json.workspace = true
filetime = "0.2"
